name: indigo_rhapsody_dupli
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.0.0+103

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  algolia: 1.1.1
  app_links: 6.3.2
  app_links_platform_interface: 2.0.2
  auto_size_text: 3.0.0
  awesome_snackbar_content: ^0.1.3
  cached_network_image: 3.4.1
  carousel_slider: 5.0.0
  cherry_toast: ^1.10.1
  chewie: 1.8.5
  cloud_firestore: ^5.6.5
  collection: 1.19.0
  crypto: ^3.0.3
  phonepe_payment_sdk: ^2.0.3
  csslib: 0.17.3
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: 8.1.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_rating_bar: 4.0.1
  flutter_staggered_grid_view: 0.7.0
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  functions_client: 2.3.2
  geocoding: ^2.1.1
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  gotrue: 2.8.4
  hive: 2.2.3
  html: 0.15.4
  http: 1.2.2
  image_picker: 1.1.2
  intl: 0.19.0
  json_path: 0.7.2
  lottie: 2.7.0
  mailer: ^6.0.1
  mime_type: 1.0.0
  open_file: ^3.3.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  pdf: ^3.3.0
  photo_view: 0.15.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  postgrest: 2.1.4
  provider: 6.1.2
  realtime_client: 2.2.1
  rxdart: 0.27.7
  # share: ^2.0.4
  shared_preferences: 2.3.2
  sign_in_with_apple: 6.1.2
  smooth_page_indicator: 1.1.0
  sqflite: 2.3.3+1
  storage_client: 2.0.3
  stream_transform: 2.1.0
  substring_highlight: 1.0.33
  supabase: 2.3.0
  supabase_flutter: 2.6.0
  syncfusion_flutter_pdf: ^22.2.12
  timeago: 3.6.1
  universal_io: 2.2.2
  url_launcher: 6.3.0
  in_app_update:

  upgrader:

  package_info_plus:

  url_launcher_windows: 3.1.2
  # video_player: 2.9.2
  video_player_android:
  webview_flutter: 4.9.0

dependency_overrides:
  http: 1.2.2
  intl: 0.19.0
  rxdart: 0.27.7
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/images/app_launcher_icon.webp"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: "MyFlutterApp"
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
          weight: 500

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: NewShoppingBag
      fonts:
        - asset: assets/fonts/NewShoppingBag.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
